# Generated by Django 4.1.7 on 2023-05-14 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('experience', models.IntegerField()),
                ('partner', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoundModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.roundmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mvp_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp1', to='tournament.teammodel')),
                ('mvp_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp2', to='tournament.teammodel')),
            ],
        ),
        migrations.CreateModel(
            name='ParticantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did_attend', models.BooleanField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.playermodel')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.teammodel')),
            ],
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_score', to='tournament.scoremodel')),
                ('result_team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_score', to='tournament.scoremodel')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.roundmodel')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='tournament.teammodel')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='tournament.teammodel')),
            ],
        ),
    ]
