# Generated by Django 4.1.7 on 2023-05-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_playermodel_matchup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='matchup',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
