# Generated by Django 4.1.7 on 2023-05-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_playermodel_matchup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='matchup',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='partner',
            field=models.TextField(default=None, null=True),
        ),
    ]
