# Generated by Django 4.1.7 on 2023-05-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_alter_playermodel_matchup_alter_playermodel_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
