# Generated by Django 4.1.7 on 2023-05-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_groupmodel_remove_playermodel_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundmodel',
            name='round_num',
            field=models.IntegerField(default=0),
        ),
    ]
