# Generated by Django 4.1.7 on 2023-06-11 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_playermodel_attending'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParticantModel',
            new_name='ParticipantModel',
        ),
        migrations.AddField(
            model_name='scoremodel',
            name='points_team_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoremodel',
            name='points_team_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scoremodel',
            name='mvp_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp1', to='tournament.playermodel'),
        ),
        migrations.AlterField(
            model_name='scoremodel',
            name='mvp_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp2', to='tournament.playermodel'),
        ),
    ]
