# Generated by Django 4.1.7 on 2023-06-12 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_rename_particantmodel_participantmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoremodel',
            name='points_team_2',
        ),
    ]
