# Generated by Django 4.1.7 on 2023-06-12 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_alter_gamemodel_result_team_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='team_1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='tournament.teammodel'),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='team_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='tournament.teammodel'),
        ),
    ]
